### ISSUE TITLE
Change template editor url 

### ISSUE THREAD

**Issue by dnwick** [wso2/streaming-integrator-tooling#10]
**Description:**
Currently it prints and accessed as Template Editor Started on : http://10.100.5.218:9390/template-server. We need to change the url to http://10.100.5.218:9390/template-editor

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AnuGayan** [comment]
This was fixed by wso2/carbon-analytics#1723
