### ISSUE TITLE
ETL Wizard - Empty password for rdbms cdc source not allowed

### ISSUE THREAD

**Issue by sybernix** [wso2/streaming-integrator-tooling#112]
**Description:**
We can have a user without password in databases. However, ETL wizard mandates that we provide a value for password

<img width="1680" alt="Screenshot 2020-08-25 at 09 50 22" src="https://user-images.githubusercontent.com/24491207/91122681-86504580-e6b8-11ea-99a5-7251a297143f.png">

**Affected Product Version:**
1.1.0

**Comment by lasanthaS** [comment]
This happens due to the required parameter annotation at the connector level. If a parameter is defined as `optional=false` it should have a non-empty value. Hence this needs to be fixed at the connector level, making the parameter optional and an empty string default value.

**Comment by lasanthaS** [comment]
Or else what we can do is showing all the mandatory fields as of the above screenshot, but make them non-required fields. WDYT? 

@niruhan @sajithshn @CharukaK

**Comment by niruhan** [comment]
Is it possible to pass an empty string from the UI? I think that is how we are handling DBs without password when writing the Siddhi app `password=""`

**Comment by niruhan** [comment]
Hmm if we allow empty string then we cannot verify mandatory fields neh..

**Comment by niruhan** [comment]
I have three ideas.
1. Make password field a special case and allow empty string/null to be passed.
2. Provide a checkbox for user to enable/disable the field
3. Allow users to proceed without blocking if they don't provide mandatory fields. But before moving to the next window, throw a warning message box saying these mandatory fields were left empty

**Comment by dnwick** [comment]
if its mandatory and if its a password field we can have check box to allow empty values since technically that is possible. I do not think in other cases we need that coz if its mandatory we need to provide a value . WDYT ?

**Comment by lasanthaS** [comment]
@dnwick @niruhan What about making the password field an optional and have an empty string as the default parameter?

**Comment by dnwick** [comment]
@lasanthaS normally password is mandatory right ? so IMO we should not change it in the backend rather handle it in the client side
