### ISSUE TITLE
ETL Wizard - CDC Source operation not validated

### ISSUE THREAD

**Issue by sybernix** [wso2/streaming-integrator-tooling#113]
**Description:**
We only allow insert, delete, update. However, through the ETL wizard I can pass any string into operation
<img width="1680" alt="Screenshot 2020-08-25 at 09 52 18" src="https://user-images.githubusercontent.com/24491207/91122849-f8288f00-e6b8-11ea-9d40-6a5acd257b57.png">

**Affected Product Version:**
1.1.0

**Comment by lasanthaS** [comment]
ATM enums and expected values cannot be set via the extension parameter definition. Hence this is not supported at the moment. To properly fix this, there must be a  change in the siddhi-core level to define expected values for a particular parameter.
