### ISSUE TITLE
Connect to server for error store explorer improvement

### ISSUE THREAD

**Issue by niruhan** [wso2/streaming-integrator-tooling#119]
**Description:**
When connecting to server for error store explorer we enter the server connection details in the following form
<img width="1680" alt="Screenshot 2020-09-07 at 14 16 01" src="https://user-images.githubusercontent.com/24491207/92368140-f4632680-f114-11ea-9c9c-eab9796890cf.png">

After entering all the values pressing enter does not proceed to connect. We have ti manually click the button "Connect"

**Suggested Labels:**
improvement

**Affected Product Version:**
1.1.0

**Comment by dnwick** [comment]
I think this is fine. User can mistakenly type values and also this is gonna introduce unnecessary complex validations.
