### ISSUE TITLE
Doc Feedback: Streaming Integrator Tooling

### ISSUE THREAD

**Issue by RukshiW** [wso2/streaming-integrator-tooling#129]
@vraghu1983 commented on [Tue Mar 24 2020](https://github.com/wso2/docs-ei/issues/1253)

Location : https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/quick-start-guide-101/
Went to the GitHub link for this and then tried to do a mvc clean install for Streaming Integrator Tooling component as I need to do a Siddhi app. 

However, facing this error. 
Can someone please let me know the correct way to do this etc.. 
![Screenshot - 24-03-2020 , 13_41_11](https://user-images.githubusercontent.com/11383924/77405431-33a4f180-6dd9-11ea-9921-12b208edc582.png)

**Comment by dnwick** [comment]
@RukshiW is this still valid ? I cant seem to go the link https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/quick-start-guide-101/ . if not shall we close this ?

**Comment by RukshiW** [comment]
Please check the revamped Getting Started guide [1]. It explains how to download Streaming Integrator Tooling as a Zip file.

[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/quick-start-guide/getting-started/download-install-and-start-si/#!
