### ISSUE TITLE
Nothing happens when trying to deploy a siddhi app to the server

### ISSUE THREAD

**Issue by CharukaK** [wso2/streaming-integrator-tooling#15]
**Description:**
When trying to deploy a siddhi app to the server no output is registered
Nothing is registered in the network section in Chrome DevTools when monitored while clicking on the deploy option 

**Suggested Labels:**
Severity/Critical, Priority/High

**Affected Product Version:**
1.0.0-m2

**OS, DB, other environment details and versions:**    
macOS Mojave version 10.14.6

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/carbon-analytics/pull/1732
