### ISSUE TITLE
Editor does not finish loading in Windows

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator-tooling#158]
**Description:**
After starting the tooling server in Windows 10, when you navigate to http://localhost:9390/editor it shows the page below forever. 
<img width="1440" alt="Screen Shot 2021-03-15 at 7 31 36 PM" src="https://user-images.githubusercontent.com/7592890/111166801-7e111680-85c6-11eb-8326-e3c13e9e3a5b.png">

Browser console:
<img width="1440" alt="Screen Shot 2021-03-15 at 7 41 05 PM" src="https://user-images.githubusercontent.com/7592890/111166821-86695180-85c6-11eb-8f45-79f2334083ab.png">

No other errors were seen on the SI tooling log.

**Affected Product Version:**
wso2si-tooling-4.0.0-SNAPSHOT
This is a fresh SI tooling pack, downloaded from the build [1] with org.wso2.carbon.siddhi.editor.core_3.0.52.jar patched as follows.
carbon-analytics tag v3.0.52 + [2] applied as a patch

[1] https://wso2.org/jenkins/view/products/job/products/job/streaming-integrator/640/
[2] https://github.com/wso2/carbon-analytics/pull/1920

**OS, DB, other environment details and versions:**    
Windows 10 Pro
Google chrome Version 55.0.2883.87 (64-bit)

**Comment by ramindu90** [comment]
This is working as expected.
