### ISSUE TITLE
[Async API Generation] Need to check why source/sink properties coming into the code with double/single chrods 

### ISSUE THREAD

**Issue by dnwick** [wso2/streaming-integrator-tooling#177]
**Description:**
Need to check why above happening and try to get the values without chords

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AnuGayan** [comment]
This is not a blocker and the already implemented solution is there in the source. Need to check and validate whether it is the best solution that can provide

**Comment by dnwick** [comment]
Sice we have a fix for now demoting the priority
