### ISSUE TITLE
http server client is not working

### ISSUE THREAD

**Issue by pmishanth** [wso2/streaming-integrator-tooling#200]
**Description:**
 [echo] Starting HTTP Server in http://localhost:8080/abc
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: org/osgi/framework/FrameworkUtil
     [java]     at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:92)
     [java]     at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:61)
     [java]     at org.wso2.si.http.server.HttpServerListenerHandler.<clinit>(Unknown Source)
     [java]     at org.wso2.si.http.server.HttpServerMain.main(Unknown Source)
     [java] Caused by: java.lang.ClassNotFoundException: org.osgi.framework.FrameworkUtil
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
     [java]     ... 4 more
     [java] Java Result: 1

I got error message while trying this step:{WSO2SIToolingHome}/samples/sample-clients/http-server and run the "ant"

**Comment by AnuGayan** [comment]
https://github.com/wso2/streaming-integrator-tooling/pull/202
