### ISSUE TITLE
Tour Guide does not work intermittently

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator-tooling#28]
**Description:**
I tried 'Simulation' tour and got stuck at following step as the guide didn't move to next step on its own.
<img width="1391" alt="Screen Shot 2019-09-27 at 7 58 18 PM" src="https://user-images.githubusercontent.com/7592890/65777641-0d700300-e162-11e9-92a2-fb86969074e2.png">
After I selected a stream from the drop-down multiple times, next step appeared but in a broken way as shown in the image below:
<img width="1384" alt="Screen Shot 2019-09-27 at 7 59 46 PM" src="https://user-images.githubusercontent.com/7592890/65777701-2d072b80-e162-11e9-9c5d-8e9a96230ea1.png">

Also, in a Windows 10 (Chrome Browser), it got stuck at below step:
![tour-guide2](https://user-images.githubusercontent.com/7592890/65777813-588a1600-e162-11e9-9620-e894ee304bab.png)

**Affected Product Version:**
SI tooling 1.0.0-alpha

**OS, DB, other environment details and versions:** 
Env 01:
Mac OS 10.13.1, 
Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
Env 02:
Windows 10 Pro
Browser: Version 77.0.3865.90 (Official Build) (64-bit)

**Steps to reproduce:**
Start a fresh SI tooling pack and try the tour guide.

**Comment by dnwick** [comment]
we tested tour guide on latest and have not came across this.
