### ISSUE TITLE
[BUILD] Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.3

### ISSUE THREAD

**Issue by oscarvesga** [wso2/streaming-integrator-tooling#44]
**Description:**
The build command `mvn clean install` is failing
![image](https://user-images.githubusercontent.com/1907656/67219840-4fe9d000-f3ee-11e9-96d2-03586ca29449.png)

**Suggested Labels:**
build

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
OS:W10
maven: 3.6.1

**Steps to reproduce:**
1. clone the repo
1. cd streaming-integrator-tooling folder and execute the maven command `mvn clean install`

**Related Issues:**

**Comment by AnuGayan** [comment]
@senthuran16  Could you please look into this.

**Comment by senthuran16** [comment]
Hello @oscarvesga ,

Could you please let us know your Maven version?
There is a known issue of findbugs-maven-plugin with **Maven 3.6.x** (Find a similar issue [here](https://github.com/wso2/carbon-apimgt/issues/6002)).

If you are using Maven 3.6.x, will it be possible for you to downgrade to **Maven 3.5.4**, and try building this please?

**Comment by oscarvesga** [comment]
Hello @senthuran16 I downgrade the maven version in my SO to 3.5.4 and now I get another error.

![image](https://user-images.githubusercontent.com/1907656/67298953-a8ce6c80-f4b1-11e9-9867-2bf2ff46a60f.png)

Any idea how I can fix it?

**Comment by senthuran16** [comment]
@oscarvesga The issue has been addressed in PR #45 , and you will be able to build it now.

**Comment by oscarvesga** [comment]
@senthuran16 thank you very much, the build was success
