### ISSUE TITLE
Source not generated properly for rdbms store created in design view

### ISSUE THREAD

**Issue by sybernix** [wso2/streaming-integrator-tooling#48]
**Description:**
When we create a rdbms store in design view the siddhi source code generated is not proper. I.e the quotation marks are not being put correctly

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
streaming-integrator-tooling-1.0.0

**Steps to reproduce:**
1. Create a new siddhi app
2. go to design view
3. create a flow as follows with an rdbms table
<img width="1033" alt="Screen Shot 2019-11-22 at 10 29 58 AM" src="https://user-images.githubusercontent.com/24491207/69399290-985d1c00-0d13-11ea-963f-34ba67f4a5f0.png">
4. Switch to design view and observe the wrong quotation mark placements
<img width="1374" alt="Screen Shot 2019-11-22 at 10 30 46 AM" src="https://user-images.githubusercontent.com/24491207/69399328-c5a9ca00-0d13-11ea-9404-5253c9e334e4.png">

**Comment by dnwick** [comment]
@niruhan did we fix this ? or still there ?
